resolver: lts-15.13

packages:
  - .

extra-deps:
  - git: https://github.com/daleiz/log-store
    commit: 4cfb66be7102732c2702709cbca77723720632e8

  - git: https://github.com/daleiz/rocksdb-haskell
    commit: 109af08f95b40f458d4933e3725ecb3e59337c39

  - git: https://github.com/hstream-io/hesp.git
    commit: c817b86aec651e3e1dfcda33e8e7220e94e29033
